---
title: "CoC analysis"
author: "Gwonjin Lee"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Mean CoC across chr
```{r}
# Load necessary libraries
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)

# F

setwd("C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/B97/breakpoint/F")


# List all CSV files in your directory
file_list_F <- list.files(pattern = "*25intervals.csv") # Adjust the interval as needed

# Initialize an empty dataframe or vector for the 8th column data (distance)
column_8_data_F <- NULL

# Initialize a list to store the 9th columns (CoC)
columns_9_list_F <- list()

# Loop through each CSV file
for (i in seq_along(file_list_F)) {
  # Read the current file
  temp_df <- read.csv(file_list_F[i])
  
  # For the first file, extract the 8th column (distance)
  if (i == 1) {
    column_8_data_F <- temp_df[, 8]
  }
  
  # Extract up to the second underscore
  matches <- regmatches(file_list_F[i], regexpr("^[^_]*_[^_]*", file_list_F[i]))
  
  # Convert matches to a string
  match_str <- as.character(matches)
  
  # If a match is found, remove the last character before the second underscore
  if (nchar(match_str) > 0) {
      # Remove the last character from the match
      modified_match <- substring(match_str, 1, nchar(match_str) - 1)
  } else {

      modified_match <- file_list_F[i]
  }
  
  # Use the adjusted part of the file name for the column name
  columns_9_list_F[[modified_match]] <- temp_df[, 9]
}


# Combine the 8th column with all 9th columns from the list
# Name the first column "distance"
result_F <- data.frame(distance = column_8_data_F, do.call(cbind, columns_9_list_F))


# Remove rows where column 8 has NaN values
result_F <- subset(result_F, !is.nan(result_F[,1]))



# Calculate the mean across all columns except 'distance' for each 'distance'
mean_F <- result_F %>%
  rowwise() %>%
  dplyr::mutate(MeanCoC = mean(c_across(-distance), na.rm = TRUE)) %>%
  dplyr::select(distance, MeanCoC)

####################################################################################################################

# M

setwd("C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/B97/breakpoint/M")

# List all CSV files in your directory
file_list_M <- list.files(pattern = "*25intervals.csv") #interval can be adjusted

# Initialize an empty dataframe or vector for the 8th column data (distance)
column_8_data_M <- NULL

# Initialize a list to store the 9th columns (CoC)
columns_9_list_M <- list()

# Loop through each CSV file
for (i in seq_along(file_list_M)) {
  # Read the current file
  temp_df <- read.csv(file_list_M[i])
  
  # For the first file, extract the 8th column
  if (i == 1) {
    column_8_data_M <- temp_df[, 8]
  }
  
  # Extract up to the second underscore
  matches <- regmatches(file_list_M[i], regexpr("^[^_]*_[^_]*", file_list_M[i]))
  
  # Convert matches to a string
  match_str <- as.character(matches)
  
  # If a match is found, remove the last character before the second underscore
  if (nchar(match_str) > 0) {
      # Remove the last character from the match
      modified_match <- substring(match_str, 1, nchar(match_str) - 1)
  } else {

      modified_match <- file_list_M[i]
  }
  
  # Use the adjusted part of the file name for the column name
  columns_9_list_M[[modified_match]] <- temp_df[, 9]
}

# Combine the 8th column with all 9th columns from the list
# Name the first column "distance"
result_M <- data.frame(distance = column_8_data_M, do.call(cbind, columns_9_list_M))


# Remove rows where column 8 has NaN values
result_M <- subset(result_M, !is.nan(result_M[,1]))


# Calculate the mean across all columns (10 chromosomes) except 'distance' for each 'distance'
mean_M <- result_M %>%
  rowwise() %>%
  dplyr::mutate(MeanCoC = mean(c_across(-distance), na.rm = TRUE)) %>%
  dplyr::select(distance, MeanCoC)


############################################################################################################

# Plotting


# Merge F and M
merge_coc <- merge(mean_F, mean_M, by = "distance")
colnames(merge_coc)[2:3] <- c("F", "M")
head(merge_coc)


# Assuming your data frame is called merge_coc
long_data <- pivot_longer(merge_coc, 
                          cols = c(F, M), 
                          names_to = "sex", 
                          values_to = "MeanCoC")

head(long_data)

# Smooth Plotting with CI
B97_CoC <- ggplot(long_data, aes(x = distance, y = MeanCoC, color = sex, fill = sex)) +
  geom_smooth(method = "loess", formula = y ~ x, span = 0.4, alpha = 0, size = 1.4) + 
  geom_point(alpha = 0.2)+
  ylim(0,2) +
  xlim(0,1) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "skyblue4", size = 1) +
  scale_fill_manual(values = c("F" = "pink", "M" = "lightblue")) + # Custom colors for fills
  scale_color_manual(values = c("F" = "firebrick1", "M" = "dodgerblue2")) + # Custom colors for lines
  theme_classic() +
  labs(x = "Distance", y = "Mean CoC", title = "B97") +
  theme(axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 18),
        legend.title = element_blank() )

B97_CoC

png(filename="../plot/B97_25intervals.png", width =7, height =5, units = 'in', res = 300)
B97_CoC
dev.off()


# Line plot
B97_CoC_L <- ggplot(long_data, aes(x = distance, y = MeanCoC, color = sex, fill = sex)) +
  geom_line(size = 1.3) +
  geom_point()+
  ylim(0,2) +
  xlim(0,1) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "skyblue4", size = 1) +
  scale_fill_manual(values = c("F" = "pink", "M" = "lightblue")) + # Custom colors for fills
  scale_color_manual(values = c("F" = "firebrick1", "M" = "dodgerblue2")) + # Custom colors for lines
  theme_classic() +
  labs(x = "Distance", y = "Mean CoC", title = "B97 (25intervals)") +
  theme(axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 18),
        legend.title = element_blank() )

B97_CoC_L


ggsave(filename = "../plot/B97_25intervals_line.png",
       plot = B97_CoC_L, 
       width = 7, 
       height = 5, 
       units = 'in', 
       dpi = 300)

```




# For each chr
```{r}

library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)
library(cowplot)
library(grid)

# Assuming result_F and result_M have been defined earlier in the first section.

result_F$sex <- 'F'
result_M$sex <- 'M'

# Combine and reshape the data
combined_results <- bind_rows(result_F, result_M) %>%
  pivot_longer(cols = starts_with("chr"), names_to = "chromosome", values_to = "CoC") %>%
  mutate(chromosome = gsub("_B97", "", chromosome), # Clean chromosome names
         chromosome = factor(chromosome, levels = paste0("chr", 1:10))) # Ensure order

plot_chromosome <- function(data, chromosome_name) {
  chr_data <- filter(data, chromosome == chromosome_name)
  
  # Check if data is present
  if (nrow(chr_data) == 0) {
    cat("No data for", chromosome_name, "\n")
    return(NULL)
  }
  
  p <- ggplot(chr_data, aes(x = distance, y = CoC, color = sex)) +
    geom_smooth(method = "loess", formula = y ~ x, span = 0.5, alpha = 0, size = 1.4) +
    geom_point(alpha = 0.4) +
    ylim(0, 2) +
    xlim(0, 1) +
    geom_hline(yintercept = 1, linetype = "dashed", color = "slategray4", size = 1, alpha = 0.7) +
    scale_color_manual(values = c("F" = "firebrick1", "M" = "dodgerblue2")) +
    labs(title = paste(chromosome_name), x = "Distance", y = "CoC") +
    theme_classic() +
    theme(axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 14),
        axis.title = element_blank(),
        plot.title = element_text(size = 18),
        legend.title = element_blank(),
        legend.text = element_text(size = 17),
        legend.position = "right" )
  
  return(p)
}

# Create an empty list to store plots
plot_list <- list()

# Generate plots for each chromosome and store them in the list
for (chr in levels(combined_results$chromosome)) {
  plot_list[[chr]] <- plot_chromosome(combined_results, chr)
}

# Combine the plots
combined_plot <- wrap_plots(plot_list, ncol = 2, guides = "collect")


# Vertical text for the y-axis label, adjusted to align properly
my_text_vertical <- textGrob("Coefficient of coincidence (CoC)", 
                             x = 0.5, y = 0.5, 
                             just = "center", 
                             gp = gpar(fontsize = 19, col = "black"), 
                             rot = 90)

# Horizontal text for the x-axis label, adjusted for bottom center placement
my_text_horizontal <- textGrob("Inter-interval distance (proportion of genetic distance)", 
                               x = 0.5, y = 0.5, 
                               just = "top", 
                               gp = gpar(fontsize = 19, col = "black"))

# Layout adjustment to correctly position 'CoC' to the left of the plots and 'Distance' below the plots
combined_plot_with_texts <- cowplot::plot_grid(
  cowplot::plot_grid(my_text_vertical, combined_plot, ncol =2, rel_widths = c(0.05, 0.95)
  ),
  my_text_horizontal,
  nrow = 2,
  rel_heights = c(0.95, 0.05) 
)

# View the adjusted combined plot with axis titles
combined_plot_with_texts + 
  plot_annotation(title = "B97", theme = theme(plot.title = element_text(hjust = 0.5, size = 20)))


# Save the combined plot
ggsave("../plot/B97_CoC_eachChr.png", combined_plot_with_texts+ 
  plot_annotation(title = "B97", 
                  theme = theme(plot.title = element_text(hjust = 0.5, size = 26))), 
  width = 10, height = 14, dpi = 300, bg = "white")


```



##################################################

# DistanceCoC=1

```{r}
head(result_F)
head(result_M)

# Initialize an empty dataframe for female (F) and male (M) results
DistanceCoC_F <- data.frame(chromosome = character(), distance_F = numeric(), stringsAsFactors = FALSE)
DistanceCoC_M <- data.frame(chromosome = character(), distance_M = numeric(), stringsAsFactors = FALSE)

# Function to extract distances
extract_distances <- function(result_df, sex) {
  distances <- data.frame(chromosome = character(), distance = numeric(), stringsAsFactors = FALSE)
  
  for(col_name in names(result_df)[c(-1, -12)]) {
    idx <- which(result_df[[col_name]] >= 1.0)[1]
    if(!is.na(idx)) {
      dist <- result_df$distance[idx]
    } else {
      dist <- NA
    }
    
    distances <- rbind(distances, data.frame(chromosome = col_name, distance = dist))
  }
  
  # Rename column based on sex
  names(distances)[2] <- paste0("distance_", sex)
  return(distances)
}

# Extract distances for result_F and result_M
DistanceCoC_F <- extract_distances(result_F, "F")
DistanceCoC_M <- extract_distances(result_M, "M")

# Merge the F and M results into a final dataframe
final_distances <- merge(DistanceCoC_F, DistanceCoC_M, by = "chromosome")

# Print the final dataframe
print(final_distances)



# Reshape data to long format for easier plotting with ggplot2
long_distances <- final_distances %>%
  gather(key = "sex_distance", value = "distance", -chromosome) %>%
  dplyr::mutate(sex = ifelse(sex_distance == "distance_F", "F", "M")) %>%
  dplyr::select(-sex_distance)

write.csv(long_distances, "../B97_DistanceCoC1.csv", row.names = F)

# Calculate mean and standard error for each sex
summary_distances <- long_distances %>%
  group_by(sex) %>%
  summarise(
    mean_distance = mean(distance, na.rm = TRUE),
    se_distance = sd(distance, na.rm = TRUE) / sqrt(n())
  )

# Function to convert p-value to asterisk significance level
p_value_to_asterisks <- function(p_value) {
  if (p_value < 0.001) {
    return("***")
  } else if (p_value < 0.01) {
    return("**")
  } else if (p_value < 0.05) {
    return("*")
  } else {
    return("ns")  # Not significant
  }
}

# Perform t-test
t_test_result <- t.test(distance ~ sex, data = long_distances)
t_test_result
# Get asterisks for p-value
asterisks <- p_value_to_asterisks(t_test_result$p.value)

# Plotting
B97_distance_COC1 <- ggplot(summary_distances, aes(x = sex, y = mean_distance, fill = sex)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.9, color = "grey70") +
  geom_errorbar(aes(ymin = mean_distance - se_distance, ymax = mean_distance + se_distance),
                width = 0.15, position = position_dodge(.9), color = "grey40") +
  labs(title = "B97",
       x = "Sex",
       y = "DistanceCoC=1") +
  labs(y = expression(Distance[CoC==1])) +
  ylim(0,0.42) +
  theme_classic() +
  scale_fill_brewer(palette = "Pastel1") +
  theme(axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16),
        axis.title.x = element_blank(),
        plot.title = element_text(size = 18),
        legend.title = element_blank(),
        legend.position = "none")  # + 
annotate("text", x = 1.5, y = max(summary_distances$mean_distance + summary_distances$se_distance, na.rm = TRUE), 
           label = asterisks, size = 12)

B97_distance_COC1



ggsave(filename = "../plot/B97_distance_COC1.png",
       plot = B97_distance_COC1, 
       width = 2.5, 
       height = 4, 
       units = 'in', 
       dpi = 300)


```



# Compare distanceCoC=1 between lines
```{r}

library(multcomp)


B97coc1 <- read.csv("C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/B97/breakpoint/B97_DistanceCoC1.csv")
CML103coc1 <- read.csv("C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/CML103/breakpoint/CML103_DistanceCoC1.csv")

mergecoc1 <- rbind(B97coc1, CML103coc1)
print(mergecoc1)

mergecoc1$line <- gsub("chr[0-9]+_", "", mergecoc1$chromosome)
mergecoc1$chromosome <- gsub("_.*", "", mergecoc1$chromosome)



# Summarize your data
summary_df <- mergecoc1 %>%
  group_by(line, sex) %>%
  summarise(mean_distance = mean(distance),
            sd = sd(distance), # Calculate standard deviation
            se = sd(distance) / sqrt(n()),
            .groups = 'drop')


#ANOVA and HSD
anova_result <- aov(distance ~ line * sex, data = mergecoc1)
mergecoc1$line_sex <- with(mergecoc1, interaction(line, sex))
anova_result <- aov(distance ~ line_sex, data = mergecoc1)


tukey_result <- TukeyHSD(anova_result)
tukey_result


post_hoc <- glht(anova_result, linfct = mcp(line_sex = "Tukey"))

summary_post_hoc <- summary(post_hoc)
group_letters <- cld(post_hoc, alpha = 0.05)

# Adjust the separator to match the format in group_letters
summary_df$group_id <- with(summary_df, paste(line, sex, sep="."))

summary_df$letters <- group_letters$mcletters$Letters[match(summary_df$group_id, names(group_letters$mcletters$Letters))]


# Plot
mergecoc1p <- ggplot(summary_df, aes(x = line, y = mean_distance, fill = sex)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.7), width = 0.68, color = "grey80") +
  geom_errorbar(aes(ymin = mean_distance - se, ymax = mean_distance + se),
                position = position_dodge(width = 0.7), width = 0.15, color = "grey40") +
  geom_text(aes(label = letters, y = mean_distance + se + 0.01),
            position = position_dodge(width = 0.7), vjust = 0, size = 6) +
  labs(y = expression(Distance[CoC==1])) +
  theme_classic() +
  scale_fill_brewer(palette = "Pastel1") +
  theme(axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 16),
        axis.title.y = element_text(size = 17),
        axis.title.x = element_blank(),
        plot.title = element_text(size = 18),
        legend.text = element_text(size = 15),
        legend.title = element_blank())

mergecoc1p


ggsave(filename = "C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/B97/breakpoint/plot/B97_CML103_COC1.png",
       plot = mergecoc1p, 
       width = 6, 
       height = 4, 
       units = 'in', 
       dpi = 300)

####

# point and error bar plot


COC1_point <- ggplot(summary_df, aes(x = line, y = mean_distance, fill = sex, color = sex, group = interaction(line, sex))) +
  geom_errorbar(aes(ymin = mean_distance - sd, ymax = mean_distance + sd),
                position = position_dodge(width = 0.7), width = 0.4, size = 1) +
  geom_point(position = position_dodge(width = 0.7), size = 9, shape = 21, color = "grey80") +
  geom_text(aes(label = letters, y = mean_distance + sd + 0.02),
            position = position_dodge(width = 0.7), vjust = 0, size = 6, color ="grey20") +
  labs(y = expression(Distance[CoC==1])) +
  theme_classic() +
  ylim(0, 0.5) +
  scale_color_manual(values = c("F" = "firebrick1", "M" = "dodgerblue2")) +
  scale_fill_manual(values = c("F" = "firebrick1", "M" = "dodgerblue2")) +
  theme(axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 16),
        axis.title.y = element_text(size = 17),
        axis.title.x = element_blank(),
        plot.title = element_text(size = 18),
        legend.text = element_text(size = 15),
        legend.title = element_blank())

COC1_point

ggsave("C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/B97/breakpoint/plot//B97_CML103_COC1_point.png", plot = COC1_point, width = 6.5, height = 4, dpi = 300)




```

##################################################


# CoC Distance=minimum 

```{r}

setwd("C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/B97/breakpoint/")

# Function to extract CoC values at minimum distances
extract_coc_at_min_distance <- function(result_df, sex) {
    coc_at_min_distance <- data.frame(chromosome = character(), 
                                      CoC_value = numeric(), 
                                      stringsAsFactors = FALSE)
    
    for(col_name in names(result_df)[c(-1,-12)]) { # Skipping the first column (distance)
        # Find the row with the minimum non-NA distance
        min_distance_row <- which.min(result_df$distance[!is.na(result_df[[col_name]])])
        if(length(min_distance_row) > 0 && !is.na(min_distance_row)) {
            coc_value <- result_df[[col_name]][min_distance_row]
        } else {
            coc_value <- NA
        }
        
        coc_at_min_distance <- rbind(coc_at_min_distance, 
                                     data.frame(chromosome = col_name, 
                                                CoC_value = coc_value))
    }
    
    # Rename column based on sex
    names(coc_at_min_distance)[2] <- paste0("CoC_value_", sex)
    return(coc_at_min_distance)
}

# Extract CoC values at minimum distances for result_F and result_M
CoC_at_min_distance_F <- extract_coc_at_min_distance(result_F, "F")
CoC_at_min_distance_M <- extract_coc_at_min_distance(result_M, "M")

# Merge the F and M results into a final dataframe
final_coc_at_min_distance <- merge(CoC_at_min_distance_F, CoC_at_min_distance_M, by = "chromosome")

# Print the final dataframe
print(final_coc_at_min_distance)


##########
# prepare Plotting

library(tidyverse)

# Assuming final_coc_at_min_distance is your current dataframe

# Reshape data to long format for easier plotting with ggplot2
long_coc <- final_coc_at_min_distance %>%
  pivot_longer(cols = starts_with("CoC_value"), names_to = "sex", values_to = "CoC_value") %>%
  mutate(sex = sub("CoC_value_", "", sex))

# Write the reshaped data to a CSV file
write.csv(long_coc, "B97_CoC_Min.csv", row.names = FALSE)

# Calculate mean and standard error for each sex across all chromosomes
summary_coc <- long_coc %>%
  group_by(sex) %>%
  summarise(
    mean_CoC_value = mean(CoC_value, na.rm = TRUE),
    se_CoC_value = sd(CoC_value, na.rm = TRUE) / sqrt(n())
  )

# Perform t-test on CoC values between sexes
t_test_result <- t.test(CoC_value ~ sex, data = long_coc)

# Function to convert p-value to asterisk significance level
p_value_to_asterisks <- function(p_value) {
  if (p_value < 0.001) {
    return("***")
  } else if (p_value < 0.01) {
    return("**")
  } else if (p_value < 0.05) {
    return("*")
  } else {
    return("ns")  # Not significant
  }
}


# Get asterisks for p-value
asterisks <- p_value_to_asterisks(t_test_result$p.value) # Re-use the provided function

# Plotting
coc_plot <- ggplot(summary_coc, aes(x = sex, y = mean_CoC_value, fill = sex)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.9, color = "grey70") +
  geom_errorbar(aes(ymin = mean_CoC_value - se_CoC_value, ymax = mean_CoC_value + se_CoC_value),
                width = 0.15, position = position_dodge(0.7), color = "grey40") +
  labs(title = "B97",
       x = "Sex",
       y = "Mean CoC Value") +
  labs(y = expression(CoC[Distance==minimum])) +
  ylim(0,0.4) +
  theme_classic() +
  scale_fill_brewer(palette = "Pastel1") +
  theme(axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 14),
        axis.title.y = element_text(size = 16),
        axis.title.x = element_blank(),
        plot.title = element_text(size = 18),
        legend.title = element_blank(),
        legend.position = "none") #+
#  annotate("text", x = 1.5, y = max(summary_coc$mean_CoC_value + summary_coc$se_CoC_value, na.rm = TRUE), 
#           label = asterisks, size = 5) # Adjust size as needed

print(coc_plot)

# Save the plot
ggsave("C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/B97/breakpoint/plot//B97_CoC_plot.png", plot = coc_plot, width = 2.5, height = 4, dpi = 300)



###


```


# Compare CoC Distance=minimum between lines
```{r}

library(multcomp)
library(ggplot2)
library(dplyr)


B97cocmin <- read.csv("C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/B97/breakpoint/B97_CoC_Min.csv")
CML103cocmin <- read.csv("C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/CML103/breakpoint/CML103_CoC_Min.csv")

mergecocmin <- rbind(B97cocmin, CML103cocmin)
print(mergecocmin)

mergecocmin$line <- gsub("chr[0-9]+_", "", mergecocmin$chromosome)
mergecocmin$chromosome <- gsub("_.*", "", mergecocmin$chromosome)



# Summarize the data
cocmin_summary_df <- mergecocmin %>%
  group_by(line, sex) %>%
  summarise(mean_CoCmin = mean(CoC_value, na.rm = TRUE),  # Ensure na.rm is TRUE if NA values can occur
            sd = sd(CoC_value, na.rm = TRUE), 
            se = sd(CoC_value, na.rm = TRUE) / sqrt(n()),  # Same here
            .groups = 'drop')  # Ensures the result is not grouped

# ANOVA and Tukey HSD Post-hoc test for interaction between line and sex
anova_result <- aov(CoC_value ~ line * sex, data = mergecocmin)

# Tukey HSD directly on the anova_result of the interaction model
tukey_result <- TukeyHSD(anova_result, "line:sex")



# Ensure the line_sex column exists in mergecocmin
mergecocmin$line_sex <- with(mergecocmin, interaction(line, sex))

# Redefine ANOVA model using the interaction variable directly
anova_result_interact <- aov(CoC_value ~ line_sex, data = mergecocmin)

# Use glht with the newly defined ANOVA model
glht_model <- glht(anova_result_interact, linfct = mcp(line_sex = "Tukey"))

summary_post_hoc <- summary(glht_model)
group_letters <- cld(glht_model, alpha = 0.05)

# Add the group letters to the summary_df
cocmin_summary_df$group_id <- with(cocmin_summary_df, paste(line, sex, sep="."))  # Ensure separator matches the one used in `interaction()`
cocmin_summary_df$letters <- group_letters$mcletters$Letters[match(cocmin_summary_df$group_id, names(group_letters$mcletters$Letters))]

cocmin_summary_df

# Plot
ggplot(cocmin_summary_df, aes(x = line, y = mean_CoCmin, fill = sex)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.7), width = 0.68, color = "grey80") +
  geom_errorbar(aes(ymin = mean_CoCmin - se, ymax = mean_CoCmin + se),
                position = position_dodge(width = 0.7), width = 0.15, color = "grey40") +
  geom_text(aes(label = letters, y = mean_CoCmin + se + 0.01),
            position = position_dodge(width = 0.7), vjust = 0, size = 6) +
  labs(y = expression(CoC[Distance==minimum])) +
  theme_classic() +
  scale_fill_brewer(palette = "Pastel1") +
  theme(axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 16),
        axis.title.y = element_text(size = 17),
        axis.title.x = element_blank(),
        plot.title = element_text(size = 18),
        legend.text = element_text(size = 15),
        legend.title = element_blank())

# Save the plot
ggsave("C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/B97/breakpoint/plot/B97_CML103_COCmin.png", 
       plot = last_plot(), width = 5.5, height = 4, units = 'in', dpi = 300)




###########
# only for lines regardless of sexes



# Summarize the data by line only
cocmin_line_summary_df <- mergecocmin %>%
  group_by(line) %>%
  summarise(mean_CoCmin = mean(CoC_value, na.rm = TRUE),
            se = sd(CoC_value, na.rm = TRUE) / sqrt(n()),
            .groups = 'drop')


# Ensure 'line' is treated as a factor
mergecocmin$line <- as.factor(mergecocmin$line)

# ANOVA for line (without interaction with sex)
anova_result_line <- aov(CoC_value ~ line, data = mergecocmin)

# It might not be necessary to use mcp(line = "Tukey") directly if there's an issue, so let's try without specifying mcp() explicitly
glht_model_line <- glht(anova_result_line, linfct = mcp(line = "Tukey"))

# If the above line still causes issues, you can try this alternative approach:
# glht_model_line <- glht(anova_result_line, linfct = mcp(line = "Tukey"), alternative = "two.sided")

# Proceed only if glht_model_line is successfully created
if(exists("glht_model_line")) {
  summary_post_hoc_line <- summary(glht_model_line)
  group_letters_line <- cld(glht_model_line, alpha = 0.05)
  
  # Continue with your summary and plotting code
}



# ANOVA and Tukey HSD Post-hoc test for line only (no interaction with sex)
anova_result_line <- aov(CoC_value ~ line, data = mergecocmin)

# Tukey HSD post-hoc for line
tukey_result_line <- TukeyHSD(anova_result_line)

# Use glht for line comparisons
glht_model_line <- glht(anova_result_line, linfct = mcp(line = "Tukey"))
summary_post_hoc_line <- summary(glht_model_line)
group_letters_line <- cld(glht_model_line, alpha = 0.05)

# Add the group letters to the line summary dataframe
cocmin_line_summary_df$letters <- group_letters_line$mcletters$Letters[match(cocmin_line_summary_df$line, names(group_letters_line$mcletters$Letters))]


# Plotting for line only
ggplot(cocmin_line_summary_df, aes(x = line, y = mean_CoCmin, fill = line)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.9, color = "grey80") +
  geom_errorbar(aes(ymin = mean_CoCmin - se, ymax = mean_CoCmin + se),
                width = 0.26, color = "grey40") +
  geom_text(aes(label = letters, y = mean_CoCmin + se + 0.01), vjust = 0, size = 6) +
  labs(y = "", x = "") +
  labs(y = expression(CoC[Distance==minimum])) +
  theme_classic() +
  scale_fill_brewer(palette = "Pastel1") +
  theme(axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 16),
        axis.title.y = element_text(size = 17),
        plot.title = element_text(size = 18),
        legend.text = element_text(size = 15),
        legend.title = element_blank(),
        legend.position = "none")  # Hide the legend as it's redundant in this case

# Save the plot
ggsave("C:/Users/Gwonjin Lee/OneDrive - University of Florida/Project/Maize/GBS_analysis/linkage/B97/breakpoint/plot/B97_CML103_COCmin_by_line.png", 
       plot = last_plot(), width = 2.5, height = 4, units = 'in', dpi = 300)





```




